# git
alias gco='git checkout'
alias gitk='gitk &'
alias gb='git branch -vv'
alias gba='git branch -avv'
alias gcb='git checkout -b'
alias gp='git pull'
alias gst='git status'
alias gf='git fetch'
alias gcm='git commit -m'
alias gd='git diff'
alias gpo='git push origin'
